### PR TITLE
Revving the version

### PR DESCRIPTION
**Pull request by alexwnovak**

### CODE REVIEW

**Comment by ajorians** [comment]
OK; seems fine by me.  Though you sure it isn't a breaking change?  In that it looks like it flagged things that the previous version didn't.  But maybe I didn't test perfectly.  Oh well 👍 :smiley:

**Comment by alexwnovak** [comment]
Hmmmmmmmm. Did the Identity project not throw those errors before?

**Comment by ajorians** [comment]
> Hmmmmmmmm. Did the Identity project not throw those errors before?

That or I didn't make a build since my last commit.  But eitherway we will want to fix those errors! :smiley:  So go for it! :smiley:

**Comment by alexwnovak** [comment]
I run v1.5.0 locally, and running that guy against the Identity repo and it found 27 errors, so I don't think I introduced them (whew).

**Comment by ajorians** [comment]
> I run v1.5.0 locally, and running that guy against the Identity repo and it found 27 errors, so I don't think I introduced them (whew).

Well OK.  I see you commented out the `const` keyword: https://github.com/TechSmith/Tools-Windows-Build-HardCodedStringCheckerSharp/pull/7/files#diff-81880da64ef06c3885909e1691e0b053R257 and I see that is creating hits:
image

I figure you have a plan for that.  But OK.  You can keep this version a maintenance version if you feel that is best! :smiley:

**Pull request merged**
